# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: like.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='like.proto',
  package='like',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlike.proto\x12\x04like\"-\n\x0bLikeRequest\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x11\n\tregion_id\x18\x02 \x01(\t\"<\n\x0cLikeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02code\x18\x03 \x01(\x05b\x06proto3'
)

_LIKEREQUEST = _descriptor.Descriptor(
  name='LikeRequest',
  full_name='like.LikeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='like.LikeRequest.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_id', full_name='like.LikeRequest.region_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=20,
  serialized_end=65,
)

_LIKERESPONSE = _descriptor.Descriptor(
  name='LikeResponse',
  full_name='like.LikeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='like.LikeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='like.LikeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='like.LikeResponse.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=67,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['LikeRequest'] = _LIKEREQUEST
DESCRIPTOR.message_types_by_name['LikeResponse'] = _LIKERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LikeRequest = _reflection.GeneratedProtocolMessageType('LikeRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIKEREQUEST,
  '__module__' : 'like_pb2'
})
_sym_db.RegisterMessage(LikeRequest)

LikeResponse = _reflection.GeneratedProtocolMessageType('LikeResponse', (_message.Message,), {
  'DESCRIPTOR' : _LIKERESPONSE,
  '__module__' : 'like_pb2'
})
_sym_db.RegisterMessage(LikeResponse)
